composer.json
Allow use of newest PHP features.
=> Update php version to 7.1

src/Import/Nodejs/FileResolver.php, test/Import/Nodejs/FileResolverTest.php
This was something I skipped previously since I saw no need for it. But it seems this can be useful.
=> Added support for different node_modules locations

src/ConfigInterface.php, src/FileConfig.php, src/Packer.php, test/FileConfigTest.php, test/fixtures/configs/include-paths.config.json
Added way to configure include paths using the file config. An additional key is added "include-paths" to the config syntax.
=> Added way to configure include paths using the file config

src/Import/Nodejs/FileResolver.php, src/Packer.php, test/Import/BuiltIn/JsImportCollectorTest.php, test/Import/BuiltIn/TsImportCollectorTest.php, test/Import/Nodejs/FileResolverTest.php
Because of DI it is better to just inject the config rather than values from it.
=> Made file resolver use config directly instead of values from it

src/Bundler/Pipeline/ContentPipeline.php, src/Bundler/PipelineBundler.php, src/Cache/CachedImportCollector.php, src/File.php, src/FileSystem/FileReader.php, src/Import/BuiltIn/AngularImportCollector.php, src/Import/BuiltIn/JsImportCollector.php, src/Import/BuiltIn/LessImportCollector.php, src/Import/BuiltIn/TsImportCollector.php, src/Import/Nodejs/FileResolver.php, test/FileTest.php
Made dealing with absolute paths more uniform so absolute paths work better. This should save a lot of duplicate code everywhere.
=> Made dealing with absolute paths more uniform

src/Packer.php, src/Plugin/AngularPlugin.php, src/Plugin/CorePlugin.php, src/Plugin/LessPlugin.php, src/Plugin/MinifyPlugin.php, src/Plugin/PluginInterface.php, src/Plugin/TsPlugin.php, test/Plugin/AngularPluginTest.php, test/Plugin/CorePluginTest.php, test/Plugin/LessPluginTest.php, test/Plugin/MinifyPluginTest.php
New plugins
- `CorePlugin`
- `MinifyPlugin`
=> Extracted two more plugins from the Packer

src/Bundler/Runner/UnixSocket.php, src/Bundler/Runner/UnixSocketFactory.php, src/Bundler/Runner/UnixSocketRunner.php, src/Config/FileConfig.php, test/Bundler/Runner/UnixSocketFactoryTest.php, test/Bundler/Runner/UnixSocketRunnerTest.php
- Additional log statements make it easier to debug potential protocol errors
- The receive loop is now non-blocking, allowing the capability of a timeout
=>  Add logging, non blocking receive 

src/Bundler/EntryPoint.php, src/Bundler/Runner/UnixSocketRunner.php, src/Import/MutableImportFinderInterface.php, src/Plugin/TsPlugin.php, test/Bundler/Pipeline/ContentPipelineTest.php, test/Cache/CachedImportCollectorTest.php, test/FileSystem/FileReaderTest.php, test/FileSystem/StringReaderTest.php, test/Import/ImportFinderTest.php
=> Ran optimize imports

src/EventListener/AngularHtmlListener.php, src/Import/BuiltIn/AngularImportCollector.php, test/EventListener/fixtures/app.component.js, test/EventListener/fixtures/test/app2.component.js
The Angular templates are searched for in the root of the project and not in the folder of the typescript file.
=> angular template paths are always relative

src/Bundler/PipelineBundler.php, src/Bundler/Runner/UnixSocketRunner.php, src/Config/ConfigInterface.php, src/Config/SimpleConfig.php, src/Config/UnixSocketType.php, src/Event/BundleEvent.php, src/Event/BundleEvents.php, src/EventListener/EnsureRunnerClosedListener.php, src/Packer.php, src/Plugin/CorePlugin.php, src/Plugin/PluginApi.php, src/Resources/build.js, test/Bundler/PipelineBundlerTest.php, test/Config/SimpleConfigTest.php, test/EventListener/EnsureRunnerClosedListenerTest.php, test/Plugin/CorePluginTest.php
Added way to kill socket after bundler is done. You can set this up so you only use the socket per process.
=> Added way to kill socket after bundler is done

src/Bundler/Runner/UnixSocketRunner.php
The previous way didn't work since the arguments were not compatible with macOS.
=> Made getting the process ID more platform independent

src/Bundler/Runner/UnixSocketRunner.php
Reverted bit of shutdown in favor of removing file. Seeing the change in PR #48 it is no longer needed to kill the process, it will kill itself once the file is gone.
=> Reverted bit of shutdown in favor of removing file

src/Bundler/PipelineBundler.php, src/Event/BundleEvents.php, src/Event/FileEvent.php, src/Event/FileEvents.php, src/EventListener/UglifyJsListener.php, src/FileSystem/FileWriter.php, src/Packer.php, src/Plugin/MinifyPlugin.php, test/Event/FileEventTest.php, test/EventListener/EnsureRunnerClosedListenerTest.php, test/EventListener/UglifyJsListenerTest.php, test/FileSystem/FileWriterTest.php, test/Plugin/MinifyPluginTest.php
Added File Events and made UglifyJS listen to that.
Do we want to do the same for the LESS? 
One downside is that embedded CSS (like in the angular bits) will not be minified since that is not written as CSS. Only as a JS, which will not do the minification.
=> Added File Events and made UglifyJS listen to that

src/Bundler/PipelineBundler.php, src/Config/ConfigInterface.php, src/Config/SimpleConfig.php, test/Bundler/PipelineBundlerTest.php, test/Config/SimpleConfigTest.php
This feature will allow you to exclude a whole part of the dependency tree. For instance, if it's being provided by a CDN or any other source.
=> Added config option to exclude certain files from the output

src/Bundler/Pipeline/ContentPipeline.php, src/Bundler/PipelineBundler.php, src/Bundler/Runner/UnixSocket.php, src/Bundler/Runner/UnixSocketRunner.php
Improved the logging of the UnixSocket a bit so it is more clear to which file it belongs. Also made the non-unix socket stuff log as info so it can be filtered from each other.
example output:
```
Writing require.js file to public/dev/require.js
+ [UnixSocketRunner] Executing UGL for /home/ydelange/projects/mijn/www/vendor/hostnet/asset-lib/src/Resources/require.js
+ [UnixSocketRunner] Starting build process
+ [UnixSocket] Sending 5044
+ [UnixSocket] Sending done
+ [UnixSocket] Reading 1 bytes
+ [UnixSocket] Reading done
+ [UnixSocket] Reading 4 bytes
+ [UnixSocket] Reading done
+ [UnixSocket] Reading 1342 bytes
+ [UnixSocket] Reading done
Checking entry-point bundle file app/Resources/assets/app.ts
* Compiling target public/dev/app.bundle.js
+ [UnixSocketRunner] Executing TSC for …
```
=> Improved logging output so that it is more hierarchical

spec/steps/uglify.spec.js, src/Builder/js/build.js, src/Builder/js/steps/uglify.js
Also fixed uglify to handle a buffer correctly
=> Made sure File content is always a buffer

appveyor.yml
Should be able to handle more php versions.
=> another appveyor fix

spec/steps/uglify.spec.js
Uglify JS updated their error messages, this caused our tests to fail
=> Fixed the assertion of the error

package.json, spec/steps/uglify.spec.js, src/Builder/Step/UglifyBuildStep.php, src/Builder/js/steps/uglify.js, src/Plugin/MinifyPlugin.php, test/Builder/Step/UglifyBuildStepTest.php, test/Builder/var-saved/build_config.json, test/Plugin/MinifyPluginTest.php
=> Use Terser instead of uglify-js

.github/workflows/main.yaml, composer.json, phpunit.xml.dist, tests/Builder/BuildConfigTest.php, tests/Builder/BuildFilesTest.php, tests/Builder/BundlerTest.php, tests/Builder/OutputReaderTest.php, tests/Builder/var-saved/52/689af_dist.require.js.sources, tests/Builder/var-saved/build_config.json, tests/Cache/CachedImportCollectorTest.php, tests/Config/SimpleConfigTest.php, tests/Import/BuiltIn/JsImportCollectorTest.php, tests/Import/BuiltIn/TsImportCollectorTest.php, tests/Import/Nodejs/FileResolverTest.php, tests/Plugin/BrotliPluginTest.php, tests/Plugin/CorePluginTest.php, tests/Plugin/CssFontRewritePluginTest.php, tests/Plugin/GzipPluginTest.php, tests/Plugin/LessPluginTest.php, tests/Plugin/MinifyPluginTest.php, tests/Plugin/PluginActivatorTest.php, tests/Plugin/PluginApiTest.php, tests/Plugin/TsPluginTest.php, tests/Report/ConsoleLoggingReporterTest.php, tests/Report/ConsoleReporterTest.php
update minimum php version to 7.3
=> migrate phpunit to 9

spec/steps/ts.spec.js, src/Builder/js/steps/ts.js
not sure what the effect of these changes will be
=> changed ts.ScriptTarget from ES5 to ES2016
