src/Bundler/Processor/js/lessc.js

Compiling a test file with a source map took 11,5 seconds. Disabling it took that down to 1,35 seconds!

Disable source maps for less

---

src/Bundler/Processor/js/lessc.js

- Output is now sent to stderr instead of stdout
- Adjusted message
Original:
```
.bla is undefined
```
Now:
```
.bla is undefined
In /path/to/my/file.less on line 15
Near  [ '/* Some code */',
'.foo::before { .bla(); }',
'.foo-0-bar::before { content: "0"; }' ]
```

Better error reporting when compiling less files

---

.gitignore
src/Import/BuiltIn/TsImportCollector.php
test/Bundler/dev/104a7_dev.require.js.sources
test/Import/BuiltIn/TsImportCollectorTest.php
test/fixtures/resolver/ts/import-syntax/Multiple2.ts
test/fixtures/resolver/ts/import-syntax/main.ts

Also ignored `test/Bundler/dev/104a7_dev.require.js.sources` since it contains the absolute path of the checkout.

Fixed regex for multi line import

---

src/Bundler/Pipeline/ContentPipeline.php
src/Bundler/Pipeline/ContentPipelineInterface.php
src/Bundler/PipelineBundler.php
src/EventListener/AngularHtmlListener.php
src/Packer.php
test/Bundler/Pipeline/ContentPipelineTest.php
test/Bundler/PipelineBundlerTest.php
test/EventListener/AngularHtmlListenerTest.php

- Made `$target_file` optional
- Swapped `$file_reader` and `$target_file` because of that
- Set default value of `$target_file` to the `$cache_file`
TODO
- Not sure what do do with `AngularHtmlListener`
- Perhaps remove argument entirely?
Feedback would be awesome :smile:

Made ContentPipeline->push target_file optional

---

src/Bundler/Pipeline/ContentPipeline.php
src/Packer.php
test/Bundler/Pipeline/ContentPipelineTest.php

To prevent
```
Warning: file_put_contents(<project_dir>/var/cache/dev/assets<asset_file>): failed to open stream: No such file or directory
```
when pushing an asset through the content pipeline directly.
Cause: `assets` folder was not created in this route.

Use writer over file_put_contents, so directory will be created

---

spec/require.spec.js
spec/support/jasmine.json

Previously unit-tests were run in a fixed order causing them to depend upon each other.

Run unit-tests in a random order so they are isolated

---

src/Packer.php
src/Plugin/PluginActivator.php
test/Plugin/PluginActivatorTest.php

Just found out that the plugins were not activated in the bundle yet.
This allows the packer/bundle to use the same code.

Add PluginActivator, so the bundle can use the same code

---

src/Config/ConfigInterface.php
src/Config/FileConfig.php
test/Config/FileConfigTest.php

Currently the twig helper includes the `web` folder in the `asset_url` function, see https://github.com/hostnet/asset-bundle/blob/master/src/Twig/AssetExtension.php#L29
That results in a style tag that doesn't work.
So needs to be possible to only get the external bit.

Allow to fetch only the name of the output folder

---

composer.json
spec/chunk-processor.spec.js
spec/reply-sender.spec.js
src/Bundler/Runner/UnixSocket.php
src/Bundler/Runner/UnixSocketFactory.php
src/Bundler/Runner/UnixSocketRunner.php
src/Config/FileConfig.php
src/Resources/build.js
src/Resources/chunk-processor.js
src/Resources/reply-sender.js
test/Bundler/Runner/UnixSocketFactoryTest.php
test/Bundler/Runner/UnixSocketRunnerTest.php
test/Bundler/Runner/UnixSocketTest.php

Currently there is a problem when sending empty files to the `UnixSocketRunner`. The JavaScript side will wait for more bytes to be sent, while the php side will be waiting for the response.
This PR means
- a new protocol that sends the length of the file name separately (see protocol below)
- the `ChunkProcessor` is now written like a state machine.
- the `ChunkProcessor` can handle it if you send more bytes than asked (i.e. you can send a whole message in one go)
- a lot more test cases for `ChunkProcessor`
Do **not** merge though, PHP side is not yet included!
Current protocol for the unix socket:
- file length (32 bit, little endian byte order)
- type (3 bytes)
- file name (keep reading bytes till `\0` character)
- file (file length bytes)
New protocol
- type (3 bytes)
- file name …

[WIP] New protocol at JavaScript side

---

src/Bundler/Runner/UnixSocket.php
test/Bundler/Runner/UnixSocketTest.php

Executing
```php
socket_recv($this->socket, $buffer, 0, MSG_WAITALL);
```
returns `false`
Was expecting an empty string in that case.

Receiving 0 bytes returns false

---

src/Bundler/Runner/UnixSocketRunner.php
src/Resources/build.js

Using `nohup` works on linux, but crashes on macs with this error:
```
nohup: can't detach from console: Inappropriate ioctl for device
```
Opting to ignore the `SIGHUP` signal instead.

Ignore SIGHUP instead of using nohup

---

spec/require.spec.js
src/Resources/require.js

Originally a part of #27 by @pjordaan 
In order to reduce the size of the original pull request.

Support libraries that are already initialized

---

src/Bundler/Processor/ModuleProcessor.php
test/Bundler/Processor/ModuleProcessorTest.php
test/Bundler/Processor/expected.module.js

Perhaps doubtful that a module name will contain these characters, but it won't crash should a module name contain this.
Gotten from #27 by @pjordaan

Protect against odd characters in module name

---

src/Bundler/Processor/TsContentProcessor.php
test/Bundler/Processor/TsContentProcessorTest.php

Via #27 from @pjordaan 
Do not automatically remove . from a module name, it's not always '.ts'

Only strip .ts from module name

---

src/Import/BuiltIn/TsImportCollector.php
src/Plugin/TsPlugin.php
test/Import/BuiltIn/TsImportCollectorTest.php

From #27 via @pjordaan 
Currently some imports fail. They end up at the definition file, while a source file is available too.
For example /animations resolved to node_modules//animations/index.d.ts, while it should resolve to node_modules//bundles/platform-browser-animations.umd.js by reading the package.json.

Ignore .d.ts entirely

---

src/Bundler/Runner/UnixSocket.php

3 seconds is too low for something like uglify to run. Decreased it for debugging purposes, won't work in real life though.

Timeout should be 30 seconds

---

.travis.yml
composer.json
phpunit.xml.dist
src/Bundler/Runner/SingleProcessRunner.php

Previous result with the bridge:
```
PHPUnit 6.4.4 by Sebastian Bergmann and contributors.
Runtime:       PHP 7.1.11-1+ubuntu14.04.1+deb.sury.org+1
Configuration: /home/ydelange/projects/libs/asset-lib/phpunit.xml.dist
Testing 
...............................................................  63 / 137 ( 45%)
............................................................... 126 / 137 ( 91%)
...........                                                     137 / 137 (100%)
Time: 415 ms, Memory: 10.00MB
OK (137 tests, 348 assertions)
Remaining deprecation notices (6)
Not inheriting environment variables is deprecated since Symfony 3.3 and will always happen in 4.0. Set "Process::inheritEnvironmentVariables()" to true instead: 6x
5x in SingleProcessRunnerTest::testExecute from …
```

Added phpunit bridge to see deprecations

---

src/Resources/build.js

Removing the socket file will not close the server. Using the lib again will start a new process, so you end up with multiple servers.

Added check to close the server when the file is gone

---

src/Bundler/PipelineBundler.php
src/Config/ConfigInterface.php
src/Config/SimpleConfig.php
src/Split/OneOnOneSplittingStrategy.php
test/Bundler/PipelineBundlerTest.php
test/Config/SimpleConfigTest.php
test/Split/OneOnOneSplittingStrategyTest.php

This moves the exclusion list to the splitting strategy class. A side effect is that dependencies of dependencies are also no longer excluded, but this functionality was actually broken as it always excluded these and was not making the assumption another dependency could also require that dependency.

moved excluded list to the splitting strategy class

---

src/Split/OneOnOneSplittingStrategy.php
test/Bundler/PipelineBundlerTest.php
test/Split/OneOnOneSplittingStrategyTest.php

found out with the functional test in asset-bundle. The output file names were prefixed with the source root.

leave out source root in OneOneSplittingStrategy

---

src/Bundler/EntryPoint.php
test/Bundler/EntryPointTest.php

In some cases entry points are not JS file but will eventually resolve to JS files. This change is to make sure the extension is always `.js`.

Fixed issue with entry point having a different extension than .js

---

src/Bundler/Asset.php
src/File.php
src/Plugin/CorePlugin.php
test/Bundler/AssetTest.php
test/FileTest.php

This solves the oddly created files for .htaccess and such. I also added a processor which can 'handle' these files. Since they have no extension, they are treated as-is files.

Fixed issue with files starting with a dot

---

src/Plugin/GzipPlugin.php
test/Plugin/GzipPluginTest.php

outputs another file with .gz output that contains a gzipped variation of the file. In combination with proper settings in Apache you can provide the gzipped variation without having to zip it on the fly per request

gzip plugin added

---

src/Bundler/Pipeline/ContentPipeline.php
test/Bundler/Pipeline/ContentPipelineTest.php

Fixed issue where inline files where not being detected as changed. This was due to a recent change where the root of the dependency tree was also processed by the walker.

Fixed issue where inline files where not being detected as changed

---

src/File.php
test/FileTest.php

The previous fix was not complete enough, it wrongfully checked the full path if it started with a dot instead of the filename. This should fix that.

Fixed issue with files in folders starting with a dot

---

package.json
src/Bundler/Runner/SingleProcessRunner.php
src/Bundler/Runner/js/brotli.js
src/Bundler/Runner/js/lessc.js
src/Bundler/Runner/js/stream-stdin.js
src/Bundler/Runner/js/tsc.js
src/Bundler/Runner/js/uglify.js

I also ran into the issue that the on('data') event split a unicode character was split in 2 binary characters which failed uglify.js into minifying the code.... Moved the stdin reading to a more generic solution.

single process runner supports Brotli too

---

src/Import/BuiltIn/JsImportCollector.php
src/Import/BuiltIn/TsImportCollector.php
test/Import/BuiltIn/JsImportCollectorTest.php
test/Import/BuiltIn/TsImportCollectorTest.php

The main problem stays that the import collectors make no sense and are forced to work only on typescript or javascript. Typescript is a superset of javascript and the imports in Typescript are just plain ES6. Still ES6 needs to be transpiled to ES5 code for generic browser stuff, but the forced extension check on ts files for TsImportCollector makes very little sense.

make the import collectors a bit more reusable

---

src/Resources/require.js

I'm having a really hard time testing this (so that is why there is no test for it), so suggestions are appriciated.
Anyhow, this should prevent any overriding of the `window.require` in case you are loading from two different sources.

Do not override require/define methods if alreay defined

---

src/Cache/CachedImportCollector.php
src/File.php
src/Import/BuiltIn/AngularImportCollector.php
src/Import/BuiltIn/JsImportCollector.php
src/Import/BuiltIn/TsImportCollector.php
src/Import/Import.php
src/Import/ImportCollection.php
src/Import/ImportFinder.php

Some xdebug profiling revealed the following:
- `CachedImportCollector::collect` was be being called multiple times for the same file. Simply caching the result in memory already gave a quick boost.
- `File::clean` was quite expensive, and in most cases (for already absolute paths) it didn't really do anything. It only does something when the path contains `./` or `.\`.
- `AngularImportCollector::supports` the `substr` is slower than doing a `strrpos`.
- in some cases `in_array` is slower than doing a `foreach`
- `ImportFinder::all` using the array keys as lookup instead of the array values is a lot faster
- public access to properties is faster than calling a method, so the `Import` also has public properties.

Performance improvements

---

src/Bundler/Pipeline/ContentPipeline.php
test/Bundler/Pipeline/ContentPipelineTest.php

Doing so will result in listeners (like the minify plugin does) to trigger and since the extension is `.js` while containing serialized php, this results in errors.

Do not use writer when making cache files

---

spec/steps/css_rewrite.spec.js
src/Builder/Step/CssFontRewriteStep.php
src/Builder/js/steps/css_rewrite.js
src/Plugin/CssFontRewitePlugin.php
test/Builder/Step/CssFontRewriteStepTest.php
test/Plugin/CssFontRewitePluginTest.php

With this change a new plugin is added which can rewrite and also provider the font files in css files. This will emit them together with the css when changed so you can package fonts with a the css in a lib and they will work.

Added Font rewrite plugin to also provider the fonts in a css file

---

src/Builder/js/build.js

Because of the changes creating the file objects, it is no longer possible to pass an array and since the `BuildableFile` is not exposed, the callable can also just accept a string and wrap that.

Buildable file is not exposed

---

appveyor.yml
spec/fixtures/additional.js
spec/steps/css_rewrite.spec.js
src/Builder/js/steps/css_rewrite.js

Do not use windows line endings in css paths. This breaks the CSS.

Do not use windows line endings in css paths

---

package.json
spec/steps/less.spec.js
src/Builder/js/steps/less.js

Upgraded less to latest version (as of writing). Also added test to make sure the JS in the less still works. From 3.0.0 and up, this is disabled by default. (see http://lesscss.org/usage/#less-options-enable-inline-javascript-deprecated- )

Upgraded less to 3.8.0

---

spec/require.spec.js
src/Builder/js/require.js
src/Import/BuiltIn/TsImportCollector.php
src/Import/Nodejs/FileResolver.php
test/Builder/var-saved/build_config.json
test/Import/BuiltIn/TsImportCollectorTest.php
test/fixtures/resolver/ts/import-syntax/main.ts

Fixes #84 and #85
- `export * from "./file"` is now possible
- `import { X, Y, Z } from "some/directory` that has an `index` file now works too.

Allow export * from and resolving a directory with index files.

---

spec/require.spec.js
src/Builder/js/require.js

Including the file `./some/dir/my-file.js` can now be included as `./some/dir/my-file`.
calling `require` will now always try to resolve 4 different modules in the following order (call order is important here):
- no suffix (exact match)
- `*.js` (implicit .js file, default node/common-js behavior)
- `*/index` (implicit index - can be a file or a directory)
- `*/index.js` (implicit index.js, default node/common-js behavior)
(where `*` is the argument passed to `require()`)
Calling directories with a `package.json` file that defines a `main` entry point _should_ already be taken care of in a previous step.

Allow relative imports from dirs and without extensions

---

spec/steps/css_rewrite.spec.js
src/Builder/js/steps/css_rewrite.js
src/Plugin/CssFontRewitePlugin.php
test/Plugin/CssFontRewitePluginTest.php

With this PR i'm adding support for urls which contain a query or hash in their URL. An example is `font.woff?1234656#iefix`. The asset lib picked this up incorrectly, thinking it query and hash were part of the extension.
Moreover, there are two additional font formats I would like to add.

Small fixes for css font urls

---

composer.json
phpunit.xml.dist

Removes symfony/phpunit-bridge so the build does not fail on deprecation warnings anymore.

Remove symfony/phpunit-bridge

---

composer.json
src/Builder/Bundler.php

Wrapped method calls that are required in symfony 4 but no longer exist in symfony 5 in method exists.
Added symfony process component to the require instead of the require-dev because we're actively using it, so use without the bundle would break this.

Make symfony 5 compatible, symfony/process should be required.

---

src/Builder/Bundler.php

On closer inspection of the issue, this function hasn;t been useful since SF4
https://github.com/symfony/symfony/blob/4.0/src/Symfony/Component/Process/Process.php

Remove process env call, instead of checking method exists.
